pool: 
  vmImage: 'windows-latest'

steps:
  - pwsh: dotnet restore
  - pwsh: dotnet build Infor.PublicSector.Mobile.FieldWorks/Infor.PublicSector.Mobile.FieldWorks.csproj -f net7.0-android33.0 -c Release
